# Generated by Django 3.0.6 on 2020-07-09 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200709_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='video',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
