# Generated by Django 3.0.6 on 2020-07-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20200710_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='desc',
            new_name='content',
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.CharField(default='', max_length=150),
        ),
    ]
