# Generated by Django 3.0.6 on 2020-07-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_videocomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocomment',
            old_name='video',
            new_name='video_id',
        ),
    ]
