# Generated by Django 3.0.6 on 2020-07-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus_table',
            new_name='contactus',
        ),
    ]
